import Foundation
import SwiftUI

// Bridge: consumes the UniFFI-generated Swift module (produced by uniffi-bindgen)
// from the compiled libalpha_mobile.so. This file is compiled into an iOS app
// alongside the generated uniffi module.

@MainActor
@Observable
class AlphaViewModel: ObservableObject {
    // MARK: - Published state
    @Published var symbol: String = "600519"
    @Published var watchlist: [String] = ["600519", "000001"]
    @Published var apiURL: String = "http://localhost:8080"
    @Published var showError: Bool = false
    @Published var errorMessage: String = ""
    @Published var lastQuote: MarketData?
    @Published var lastAnalysis: AnalysisResult?
    @Published var isAnalyzing: Bool = false

    // MARK: - UniFFI runtime
    private let core: MobileCore  // generated by uniffi-bindgen from the Rust proc-macro API

    init(core: MobileCore) {
        self.core = core
    }

    // MARK: - Watch-list operations
    func addSymbol(_ symbol: String) {
        // Note: In a full impl the FFI export would expose
        // `add_watched` / `remove_watched`; for this scaffold we
        // merely update the local watchlist and re‑construct core.
        // The real boundary is documented in §7 of the design doc.
        self.watchlist.append(symbol)
    }

    func removeSymbol(_ symbol: String) {
        self.watchlist = self.watchlist.filter { $0 != symbol }
    }

    // MARK: - Quote
    func loadQuote() {
        Task {
            do {
                let json = try await core.quote_json(symbol: self.symbol)
                if let data = json.data(using: .utf8),
                   let md = try? JSONDecoder().decode(MarketData.self, from: data) {
                    self.lastQuote = md
                } else {
                    throw NSError(domain: "Alpha", code: 0, userInfo: [NSLocalizedDescriptionKey: "Failed to decode quote JSON"])
                }
            } catch {
                self.errorMessage = error.localizedDescription
                self.showError = true
            }
        }
    }

    // MARK: - Analyze
    func analyzeSymbol() {
        Task {
            do {
                let json = try await core.analyze_json(symbol: self.symbol)
                if let data = json.data(using: .utf8),
                   let ar = try? JSONDecoder().decode(AnalysisResult.self, from: data) {
                    self.lastAnalysis = ar
                } else {
                    throw NSError(domain: "Alpha", code: 0, userInfo: [NSLocalizedDescriptionKey: "Failed to decode analysis JSON"])
                }
            } catch {
                self.errorMessage = error.localizedDescription
                self.showError = true
            }
        }
    }

    // MARK: - Status
    func loadStatus() {
        Task {
            do {
                let json = try await core.status_json()
                // status_json returns a plain String; we just log the version
                if let version = json.components(separatedBy: "\"version\": \"").last?.components(separatedBy: "\"").first {
                    self.errorMessage = "Version: \(version)"
                }
            } catch {
                self.errorMessage = error.localizedDescription
                self.showError = true
            }
        }
    }
}

// MARK: - SwiftUI View
struct AlphaView: View {
    @StateObject private var viewModel: AlphaViewModel

    // In a real app the core instance would be created via the
    // UniFFI-generated initializer (returning Arc<MobileCore> →
    // an @MainActor-isolated reference on iOS).
    private let core: MobileCore  // generated by uniffi-bindgen

    init(core: MobileCore) {
        self.core = core
        _viewModel = StateObject(wrappedValue: AlphaViewModel(core: core))
    }

    var body: some View {
        NavigationView {
            VStack(spacing: 20) {
                // Symbol input
                HStack {
                    TextField("Symbol (e.g. 600519)", text: $viewModel.symbol)
                        .textFieldStyle(.rounded)
                    Button("Load") { viewModel.loadQuote() }
                        .buttonStyle(.borderedProminent)
                }
                .padding(.horizontal)

                if let quote = viewModel.lastQuote {
                    VStack(alignment: .leading, spacing: 8) {
                        Text("\(quote.symbol): $\(String(format: "%.2", quote.price))")
                            .font(.headline)
                        Text("Vol: \(quote.volume)")
                        Text("Bid: \(quote.bid.map { String(format: "%.2", $0 ) } ?? "N/A")")
                        Text("Ask: \(quote.ask.map { String(format: "%.2", $0 ) } ?? "N/A")")
                    }
                    .padding()
                    .background(Color(.systemGray6))
                    .cornerRadius(8)
                }

                Spacer()

                // Analyze button
                Button("Run Analysis") { viewModel.analyzeSymbol() }
                    .buttonStyle(.borderedProminent)
                    .disabled(viewModel.isAnalyzing)

                if viewModel.isAnalyzing {
                    ProgressView("Analyzing...")
                        .padding()
                }

                if let analysis = viewModel.lastAnalysis {
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Recommendation: \(analysis.recommendation)")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                        Text("Confidence: \(String(format: "%.1f", analysis.confidence))%")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                        HStack {
                            Text("Volatility: \(String(format: "%.2f", analysis.riskMetrics.volatility))")
                            Text("Max Drawdown: \(String(format: "%.2f", analysis.riskMetrics.maxDrawdown))")
                        }
                        .font(.caption)
                        .foregroundColor(.secondary)

                        ForEach(analysis.indicators) { ind in
                            VStack(alignment: .leading, spacing: 4) {
                                Text(ind.name)
                                    .font(.footnote)
                                    .bold()
                                HStack {
                                    Text("Latest: \(String(format: "%.2f", ind.values.last ?? 0))")
                                    Text("Signal: \(ind.signals.first ?? "—")")
                                }
                                .font(.caption2)
                                .foregroundColor(.secondary)
                            }
                        }
                    }
                    .padding()
                    .background(Color(.systemGray6))
                    .cornerRadius(8)
                }

                Spacer()

                // Status bar
                HStack {
                    Text("API: \(viewModel.apiURL)")
                        .font(.caption2)
                    Text("v\(ProcessInfo.processInfo.environment["CARGO_PKG_VERSION"] ?? "dev")")
                        .font(.caption2)
                }
                .padding(.bottom, 8)
            }
            .navigationTitle("Alpha — Mobile")
            .alert("Error", isPresented: $viewModel.showError) {
                Button("OK", role: .cancel) { }
            } message: {
                Text(viewModel.errorMessage)
            }
        }
    }
}